name: maps_application
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  geolocator: ^13.0.2
  http: ^1.3.0
  
  latlong2: ^0.9.1
  flutter_map: ^7.0.2
  flutter_map_location_marker: ^9.1.1
  flutter_polyline_points: ^2.1.0
  flutter_map_cancellable_tile_provider: ^3.0.2
  flutter_osm_plugin: ^1.3.6
  file_picker: ^9.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/tutorial/1/
    - assets/images/tutorial/2/
    - assets/images/tutorial/3/